title: Godot algkursus
description: Eestikeelne Godot algkursus
theme: just-the-docs

url: https://taavippp.github.io/godot

aux_links:
  Koduleht: https://taavippp.github.io/

logo: "/assets/logo.png"
color_scheme: dark
markdown: kramdown

search_enabled: true
enable_copy_code_button: true
heading_anchors: true