title: Godot algkursus
description: Eestikeelne Godot mängumootori kursus
theme: just-the-docs

url: https://taavippp.github.io/godot

aux_links:
  Godot: https://godotengine.org/
  Koduleht: https://taavippp.github.io/
  Repositoorium: https://github.com/taavippp/godot
aux_links_new_tab: true

markdown: kramdown
search_enabled: true
enable_copy_code_button: true
heading_anchors: true
mermaid:
  version: "10.8.0"

logo: "https://taavippp.github.io/godot/logo.png"
color_scheme: dark

callouts:
  todo:
    title: Poolik sisu!
    color: red
  tip:
    title: Hea teada!
    color: blue