title: Godot algkursus
description: Eestikeelne kursus, mille eesmärgiks on õpetada kasutajat Godot mängumootorit kasutama.
theme: just-the-docs

url: https://taavippp.github.io/godot

aux_links:
  Koduleht: https://taavippp.github.io/

color_scheme: dark
markdown: kramdown

search_enabled: true
enable_copy_code_button: true
heading_anchors: true